export SOURCE_URL="https://github.com/jeremy-rifkin/cpptrace/archive/refs/tags/v1.0.4.tar.gz"
export SOURCE_FILE="cpptrace-1.0.4.tar.gz"
export CMAKE_ARGS="-DBUILD_SHARED_LIBS=ON -DCPPTRACE_DEMANGLE_WITH_CXXABI=ON -DCPPTRACE_FIND_LIBDWARF_WITH_PKGCONFIG=ON -DCPPTRACE_GET_SYMBOLS_WITH_LIBDWARF=ON -DCPPTRACE_UNWIND_WITH_EXECINFO=ON -DCPPTRACE_USE_EXTERNAL_GTEST=ON -DCPPTRACE_USE_EXTERNAL_LIBDWARF=ON -DCPPTRACE_USE_EXTERNAL_ZSTD=ON"

source "../common/get_source.sh"
source "../common/cmake_build.sh"