source "./source_urls.sh"

export SOURCE_URL=${CPPTRACE_URL}
export CMAKE_ARGS="-DBUILD_SHARED_LIBS=ON -DCPPTRACE_DEMANGLE_WITH_CXXABI=ON -DCPPTRACE_FIND_LIBDWARF_WITH_PKGCONFIG=ON -DCPPTRACE_GET_SYMBOLS_WITH_LIBDWARF=ON -DCPPTRACE_UNWIND_WITH_EXECINFO=ON -DCPPTRACE_USE_EXTERNAL_GTEST=ON -DCPPTRACE_USE_EXTERNAL_LIBDWARF=ON -DCPPTRACE_USE_EXTERNAL_ZSTD=ON"

source "../common/get_source.sh"
source "../common/cmake_build.sh"