sudo install_name_tool -id "@rpath/libasprintf.0.dylib" /usr/local/lib/libasprintf.0.dylib
sudo install_name_tool -id "@rpath/libffi.7.dylib" /usr/local/lib/libffi.7.dylib
sudo install_name_tool -id "@rpath/libffi.8.dylib" /usr/local/lib/libffi.8.dylib
sudo install_name_tool -id "@rpath/libfluidsynth.3.dylib" /usr/local/lib/libfluidsynth.3.dylib
sudo install_name_tool -id "@rpath/libgettextlib-0.22.5.dylib" /usr/local/lib/libgettextlib-0.22.5.dylib
sudo install_name_tool -id "@rpath/libgettextpo.0.dylib" /usr/local/lib/libgettextpo.0.dylib
sudo install_name_tool -id "@rpath/libgettextsrc-0.22.5.dylib" /usr/local/lib/libgettextsrc-0.22.5.dylib
sudo install_name_tool -id "@rpath/libhistory.8.dylib" /usr/local/lib/libhistory.8.dylib
sudo install_name_tool -id "@rpath/libintl.8.dylib" /usr/local/lib/libintl.8.dylib
sudo install_name_tool -id "@rpath/libltdl.7.dylib" /usr/local/lib/libltdl.7.dylib
sudo install_name_tool -id "@rpath/libmp3lame.0.dylib" /usr/local/lib/libmp3lame.0.dylib
sudo install_name_tool -id "@rpath/libmpg123.0.dylib" /usr/local/lib/libmpg123.0.dylib
sudo install_name_tool -id "@rpath/libopusfile.0.dylib" /usr/local/lib/libopusfile.0.dylib
sudo install_name_tool -id "@rpath/libopusurl.0.dylib" /usr/local/lib/libopusurl.0.dylib
sudo install_name_tool -id "@rpath/libout123.0.dylib" /usr/local/lib/libout123.0.dylib
sudo install_name_tool -id "@rpath/libpcre2-16.0.dylib" /usr/local/lib/libpcre2-16.0.dylib
sudo install_name_tool -id "@rpath/libpcre2-32.0.dylib" /usr/local/lib/libpcre2-32.0.dylib
sudo install_name_tool -id "@rpath/libpcre2-8.0.dylib" /usr/local/lib/libpcre2-8.0.dylib
sudo install_name_tool -id "@rpath/libpcre2-posix.3.dylib" /usr/local/lib/libpcre2-posix.3.dylib
sudo install_name_tool -id "@rpath/libreadline.8.dylib" /usr/local/lib/libreadline.8.dylib
sudo install_name_tool -id "@rpath/libsyn123.0.dylib" /usr/local/lib/libsyn123.0.dylib
sudo install_name_tool -id "@rpath/libtextstyle.0.dylib" /usr/local/lib/libtextstyle.0.dylib
sudo install_name_tool -id "@rpath/libgme.0.dylib" /usr/local/lib/libgme.0.dylib
sudo install_name_tool -id "@rpath/libogg.0.dylib" /usr/local/lib/libogg.0.dylib
sudo install_name_tool -id "@rpath/libvorbis.0.4.9.dylib" /usr/local/lib/libvorbis.0.4.9.dylib
sudo install_name_tool -id "@rpath/libvorbisenc.2.0.12.dylib" /usr/local/lib/libvorbisenc.2.0.12.dylib
sudo install_name_tool -id "@rpath/libvorbisfile.3.3.8.dylib" /usr/local/lib/libvorbisfile.3.3.8.dylib

sudo install_name_tool -id "@rpath/libSDL2_image-2.0.0.dylib" /usr/local/lib/libSDL2_image-2.0.0.dylib
sudo install_name_tool -id "@rpath/libSDL2_ttf-2.0.0.dylib" /usr/local/lib/libSDL2_ttf-2.0.0.dylib